version: '3.3'

services:

    wpdb:
        image: mysql:5.7
        environment: 
            MYSQL_DATABASE: ${WP_DB_NAME:-wpdb}
            MYSQL_USER: ${WP_DB_USER:-wpdb}
            MYSQL_PASSWORD: ${WP_DB_PASS:-wpdb}
            MYSQL_RANDOM_ROOT_PASSWORD: '1'
        volumes: 
            - wpdb:/var/lib/mysql
        ports:
            - ${WP_DB_PORT:-3306}:3306


    wordpress:
        build: ./.docker/wordpress/
        env_file: .env
        ports: 
            - ${WP_PORT:-80}:80
        environment: 
            WORDPRESS_DB_HOST: ${WP_DB_HOST:-wpdb}
            WORDPRESS_DB_USER: ${WP_DB_USER:-wpdb}
            WORDPRESS_DB_PASSWORD: ${WP_DB_PASS:-wpdb}
            WORDPRESS_DB_NAME: ${WP_DB_NAME:-wpdb}
        volumes: 
            - .:/var/www/html/wp-content/plugins/wpvue

    vite:
        image: node:lts
        working_dir: /var/www/html/wp-content/plugins/wpvue
        command: bash -c "yarn install && yarn dev"
        env_file: .env
        ports: 
            - ${VITE_PORT:-5173}:${VITE_PORT:-5173}
        volumes: 
            - .:/var/www/html/wp-content/plugins/wpvue
        tty: true
        
volumes: 
    wpdb: