version: '3.3'

services:

    vite-build:
        image: node:lts
        working_dir: /var/www/html/wp-content/plugins/wpvue
        command: bash -c "yarn install && yarn build"
        volumes: 
            - .:/var/www/html/wp-content/plugins/wpvue